[ColorRed0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorGreen0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorBlue0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\s*?\,\s*?(\d+)\s*?\,\s*?(\d+)$" : "\3"
UpdateDivider=-1