[ColorRed0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed2]
Measure=String
String=#ColorA2#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed3]
Measure=String
String=#ColorA3#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed4]
Measure=String
String=#ColorA4#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed5]
Measure=String
String=#ColorA5#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorRed6]
Measure=String
String=#ColorA6#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\1"
UpdateDivider=-1
[ColorGreen0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen2]
Measure=String
String=#ColorA2#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen3]
Measure=String
String=#ColorA3#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen4]
Measure=String
String=#ColorA4#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen5]
Measure=String
String=#ColorA5#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorGreen6]
Measure=String
String=#ColorA6#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\2"
UpdateDivider=-1
[ColorBlue0]
Measure=String
String=#ColorA0#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue1]
Measure=String
String=#ColorA1#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue2]
Measure=String
String=#ColorA2#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue3]
Measure=String
String=#ColorA3#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue4]
Measure=String
String=#ColorA4#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue5]
Measure=String
String=#ColorA5#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1
[ColorBlue6]
Measure=String
String=#ColorA6#
RegExpSubstitute=1
Substitute="^(\d+)\,\s*?(\d+)\,\s*?(\d+)$" : "\3"
UpdateDivider=-1