[MeterBand0]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand0
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand0]), 13, (-1*(200*[MeasureBand0])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color0#
DynamicVariables=1
[MeterBand1]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand1
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand1]), 13, (-1*(200*[MeasureBand1])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color1#
DynamicVariables=1
[MeterBand2]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand2
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand2]), 14, (-1*(200*[MeasureBand2])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color2#
DynamicVariables=1
[MeterBand3]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand3
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand3]), 13, (-1*(200*[MeasureBand3])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color3#
DynamicVariables=1
[MeterBand4]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand4
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand4]), 14, (-1*(200*[MeasureBand4])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color4#
DynamicVariables=1
[MeterBand5]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand5
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand5]), 17, (-1*(200*[MeasureBand5])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color5#
DynamicVariables=1
[MeterBand6]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand6
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand6]), 14, (-1*(200*[MeasureBand6])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color6#
DynamicVariables=1
[MeterBand7]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand7
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand7]), 24, (-1*(200*[MeasureBand7])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color7#
DynamicVariables=1
[MeterBand8]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand8
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand8]), 14, (-1*(200*[MeasureBand8])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color8#
DynamicVariables=1
[MeterBand9]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand9
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand9]), 13, (-1*(200*[MeasureBand9])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color9#
DynamicVariables=1
[MeterBand10]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand10
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand10]), 17, (-1*(200*[MeasureBand10])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color10#
DynamicVariables=1
[MeterBand11]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand11
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand11]), 13, (-1*(200*[MeasureBand11])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color11#
DynamicVariables=1
[MeterBand12]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand12
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand12]), 14, (-1*(200*[MeasureBand12])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color12#
DynamicVariables=1
[MeterBand13]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand13
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand13]), 13, (-1*(200*[MeasureBand13])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color13#
DynamicVariables=1
[MeterBand14]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand14
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand14]), 24, (-1*(200*[MeasureBand14])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color14#
DynamicVariables=1
[MeterBand15]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand15
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand15]), 17, (-1*(200*[MeasureBand15])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color15#
DynamicVariables=1
[MeterBand16]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand16
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand16]), 14, (-1*(200*[MeasureBand16])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color16#
DynamicVariables=1
[MeterBand17]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand17
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand17]), 13, (-1*(200*[MeasureBand17])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color17#
DynamicVariables=1
[MeterBand18]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand18
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand18]), 14, (-1*(200*[MeasureBand18])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color18#
DynamicVariables=1
[MeterBand19]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand19
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand19]), 13, (-1*(200*[MeasureBand19])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color19#
DynamicVariables=1
[MeterBand20]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand20
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand20]), 17, (-1*(200*[MeasureBand20])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color20#
DynamicVariables=1
[MeterBand21]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand21
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand21]), 24, (-1*(200*[MeasureBand21])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color21#
DynamicVariables=1
[MeterBand22]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand22
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand22]), 14, (-1*(200*[MeasureBand22])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color22#
DynamicVariables=1
[MeterBand23]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand23
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand23]), 13, (-1*(200*[MeasureBand23])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color23#
DynamicVariables=1
[MeterBand24]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand24
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand24]), 14, (-1*(200*[MeasureBand24])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color24#
DynamicVariables=1
[MeterBand25]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand25
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand25]), 17, (-1*(200*[MeasureBand25])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color25#
DynamicVariables=1
[MeterBand26]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand26
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand26]), 14, (-1*(200*[MeasureBand26])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color26#
DynamicVariables=1
[MeterBand27]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand27
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand27]), 13, (-1*(200*[MeasureBand27])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color27#
DynamicVariables=1
[MeterBand28]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand28
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand28]), 24, (-1*(200*[MeasureBand28])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color28#
DynamicVariables=1
[MeterBand29]
Meter=Shape
X=3R
Y=200 + 20 ; The amount Y bars move up + 5
MeasureName=MeasureBand29
Shape=Rectangle 0, (100 - 20 ; The amount Y bars move up*[MeasureBand29]), 13, (-1*(200*[MeasureBand29])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color29#
DynamicVariables=1