[MeterBand0]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand0
Shape=Rectangle 0, (150 - 0*[MeasureBand0]), 20, (-1*(150*[MeasureBand0])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color0#
DynamicVariables=1
[MeterBand1]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand1
Shape=Rectangle 0, (150 - 0*[MeasureBand1]), 20, (-1*(150*[MeasureBand1])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color1#
DynamicVariables=1
[MeterBand2]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand2
Shape=Rectangle 0, (150 - 0*[MeasureBand2]), 20, (-1*(150*[MeasureBand2])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color2#
DynamicVariables=1
[MeterBand3]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand3
Shape=Rectangle 0, (150 - 0*[MeasureBand3]), 20, (-1*(150*[MeasureBand3])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color3#
DynamicVariables=1
[MeterBand4]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand4
Shape=Rectangle 0, (150 - 0*[MeasureBand4]), 20, (-1*(150*[MeasureBand4])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color4#
DynamicVariables=1
[MeterBand5]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand5
Shape=Rectangle 0, (150 - 0*[MeasureBand5]), 20, (-1*(150*[MeasureBand5])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color5#
DynamicVariables=1
[MeterBand6]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand6
Shape=Rectangle 0, (150 - 0*[MeasureBand6]), 20, (-1*(150*[MeasureBand6])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color6#
DynamicVariables=1
[MeterBand7]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand7
Shape=Rectangle 0, (150 - 0*[MeasureBand7]), 20, (-1*(150*[MeasureBand7])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color7#
DynamicVariables=1
[MeterBand8]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand8
Shape=Rectangle 0, (150 - 0*[MeasureBand8]), 20, (-1*(150*[MeasureBand8])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color8#
DynamicVariables=1
[MeterBand9]
Meter=Shape
X=3R
Y=150 + 0 + 5
MeasureName=MeasureBand9
Shape=Rectangle 0, (150 - 0*[MeasureBand9]), 20, (-1*(150*[MeasureBand9])), 3 | StrokeWidth 0 | Extend MyModifiers
MyModifiers=Fill Color #Color9#
DynamicVariables=1