[MeterReflectionBand0]
Meter=Shape
X=3
Y=200 + 20 + 15
MeasureName=MeasureBand0
Shape=Rectangle 0, (100 + 20*[MeasureBand0]), [MeterBand0:W], (200*[MeasureBand0]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color0#,0;0.0 | #Color0#,0;0.3 | #Color0#,150;1.0
DynamicVariables=1
[MeterReflectionBand1]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand1
Shape=Rectangle 0, (100 + 20*[MeasureBand1]), [MeterBand1:W], (200*[MeasureBand1]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color1#,0;0.0 | #Color1#,0;0.3 | #Color1#,150;1.0
DynamicVariables=1
[MeterReflectionBand2]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand2
Shape=Rectangle 0, (100 + 20*[MeasureBand2]), [MeterBand2:W], (200*[MeasureBand2]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color2#,0;0.0 | #Color2#,0;0.3 | #Color2#,150;1.0
DynamicVariables=1
[MeterReflectionBand3]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand3
Shape=Rectangle 0, (100 + 20*[MeasureBand3]), [MeterBand3:W], (200*[MeasureBand3]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color3#,0;0.0 | #Color3#,0;0.3 | #Color3#,150;1.0
DynamicVariables=1
[MeterReflectionBand4]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand4
Shape=Rectangle 0, (100 + 20*[MeasureBand4]), [MeterBand4:W], (200*[MeasureBand4]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color4#,0;0.0 | #Color4#,0;0.3 | #Color4#,150;1.0
DynamicVariables=1
[MeterReflectionBand5]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand5
Shape=Rectangle 0, (100 + 20*[MeasureBand5]), [MeterBand5:W], (200*[MeasureBand5]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color5#,0;0.0 | #Color5#,0;0.3 | #Color5#,150;1.0
DynamicVariables=1
[MeterReflectionBand6]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand6
Shape=Rectangle 0, (100 + 20*[MeasureBand6]), [MeterBand6:W], (200*[MeasureBand6]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color6#,0;0.0 | #Color6#,0;0.3 | #Color6#,150;1.0
DynamicVariables=1
[MeterReflectionBand7]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand7
Shape=Rectangle 0, (100 + 20*[MeasureBand7]), [MeterBand7:W], (200*[MeasureBand7]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color7#,0;0.0 | #Color7#,0;0.3 | #Color7#,150;1.0
DynamicVariables=1
[MeterReflectionBand8]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand8
Shape=Rectangle 0, (100 + 20*[MeasureBand8]), [MeterBand8:W], (200*[MeasureBand8]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color8#,0;0.0 | #Color8#,0;0.3 | #Color8#,150;1.0
DynamicVariables=1
[MeterReflectionBand9]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand9
Shape=Rectangle 0, (100 + 20*[MeasureBand9]), [MeterBand9:W], (200*[MeasureBand9]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color9#,0;0.0 | #Color9#,0;0.3 | #Color9#,150;1.0
DynamicVariables=1
[MeterReflectionBand10]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand10
Shape=Rectangle 0, (100 + 20*[MeasureBand10]), [MeterBand10:W], (200*[MeasureBand10]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color10#,0;0.0 | #Color10#,0;0.3 | #Color10#,150;1.0
DynamicVariables=1
[MeterReflectionBand11]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand11
Shape=Rectangle 0, (100 + 20*[MeasureBand11]), [MeterBand11:W], (200*[MeasureBand11]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color11#,0;0.0 | #Color11#,0;0.3 | #Color11#,150;1.0
DynamicVariables=1
[MeterReflectionBand12]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand12
Shape=Rectangle 0, (100 + 20*[MeasureBand12]), [MeterBand12:W], (200*[MeasureBand12]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color12#,0;0.0 | #Color12#,0;0.3 | #Color12#,150;1.0
DynamicVariables=1
[MeterReflectionBand13]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand13
Shape=Rectangle 0, (100 + 20*[MeasureBand13]), [MeterBand13:W], (200*[MeasureBand13]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color13#,0;0.0 | #Color13#,0;0.3 | #Color13#,150;1.0
DynamicVariables=1
[MeterReflectionBand14]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand14
Shape=Rectangle 0, (100 + 20*[MeasureBand14]), [MeterBand14:W], (200*[MeasureBand14]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color14#,0;0.0 | #Color14#,0;0.3 | #Color14#,150;1.0
DynamicVariables=1
[MeterReflectionBand15]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand15
Shape=Rectangle 0, (100 + 20*[MeasureBand15]), [MeterBand15:W], (200*[MeasureBand15]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color15#,0;0.0 | #Color15#,0;0.3 | #Color15#,150;1.0
DynamicVariables=1
[MeterReflectionBand16]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand16
Shape=Rectangle 0, (100 + 20*[MeasureBand16]), [MeterBand16:W], (200*[MeasureBand16]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color16#,0;0.0 | #Color16#,0;0.3 | #Color16#,150;1.0
DynamicVariables=1
[MeterReflectionBand17]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand17
Shape=Rectangle 0, (100 + 20*[MeasureBand17]), [MeterBand17:W], (200*[MeasureBand17]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color17#,0;0.0 | #Color17#,0;0.3 | #Color17#,150;1.0
DynamicVariables=1
[MeterReflectionBand18]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand18
Shape=Rectangle 0, (100 + 20*[MeasureBand18]), [MeterBand18:W], (200*[MeasureBand18]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color18#,0;0.0 | #Color18#,0;0.3 | #Color18#,150;1.0
DynamicVariables=1
[MeterReflectionBand19]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand19
Shape=Rectangle 0, (100 + 20*[MeasureBand19]), [MeterBand19:W], (200*[MeasureBand19]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color19#,0;0.0 | #Color19#,0;0.3 | #Color19#,150;1.0
DynamicVariables=1
[MeterReflectionBand20]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand20
Shape=Rectangle 0, (100 + 20*[MeasureBand20]), [MeterBand20:W], (200*[MeasureBand20]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color20#,0;0.0 | #Color20#,0;0.3 | #Color20#,150;1.0
DynamicVariables=1
[MeterReflectionBand21]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand21
Shape=Rectangle 0, (100 + 20*[MeasureBand21]), [MeterBand21:W], (200*[MeasureBand21]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color21#,0;0.0 | #Color21#,0;0.3 | #Color21#,150;1.0
DynamicVariables=1
[MeterReflectionBand22]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand22
Shape=Rectangle 0, (100 + 20*[MeasureBand22]), [MeterBand22:W], (200*[MeasureBand22]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color22#,0;0.0 | #Color22#,0;0.3 | #Color22#,150;1.0
DynamicVariables=1
[MeterReflectionBand23]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand23
Shape=Rectangle 0, (100 + 20*[MeasureBand23]), [MeterBand23:W], (200*[MeasureBand23]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color23#,0;0.0 | #Color23#,0;0.3 | #Color23#,150;1.0
DynamicVariables=1
[MeterReflectionBand24]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand24
Shape=Rectangle 0, (100 + 20*[MeasureBand24]), [MeterBand24:W], (200*[MeasureBand24]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color24#,0;0.0 | #Color24#,0;0.3 | #Color24#,150;1.0
DynamicVariables=1
[MeterReflectionBand25]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand25
Shape=Rectangle 0, (100 + 20*[MeasureBand25]), [MeterBand25:W], (200*[MeasureBand25]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color25#,0;0.0 | #Color25#,0;0.3 | #Color25#,150;1.0
DynamicVariables=1
[MeterReflectionBand26]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand26
Shape=Rectangle 0, (100 + 20*[MeasureBand26]), [MeterBand26:W], (200*[MeasureBand26]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color26#,0;0.0 | #Color26#,0;0.3 | #Color26#,150;1.0
DynamicVariables=1
[MeterReflectionBand27]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand27
Shape=Rectangle 0, (100 + 20*[MeasureBand27]), [MeterBand27:W], (200*[MeasureBand27]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color27#,0;0.0 | #Color27#,0;0.3 | #Color27#,150;1.0
DynamicVariables=1
[MeterReflectionBand28]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand28
Shape=Rectangle 0, (100 + 20*[MeasureBand28]), [MeterBand28:W], (200*[MeasureBand28]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color28#,0;0.0 | #Color28#,0;0.3 | #Color28#,150;1.0
DynamicVariables=1
[MeterReflectionBand29]
Meter=Shape
X=3R
Y=200 + 20 + 15
MeasureName=MeasureBand29
Shape=Rectangle 0, (100 + 20*[MeasureBand29]), [MeterBand29:W], (200*[MeasureBand29]), 3 | StrokeWidth 0 | Fill LinearGradient MyFillGradient
MyFillGradient=90 | #Color29#,0;0.0 | #Color29#,0;0.3 | #Color29#,150;1.0
DynamicVariables=1