[Title1]
Meter=String
Text=Version 1.00#CRLF#    death.crafter
FontSize=9
X=12
Y=379
FontFace=Comfortaa Bold
Angle=(Rad(270))
AntiAlias=1

[Unlicense]
Meter=Image
ImageName=#@#Images\unlicensed
ImageTint=0,0,0
H=11
W=11
X=27
Y=367

[Github]
Meter=Image
ImageName=#@#Images\github
H=25
W=25
X=12
Y=215
LeftMouseUpAction=[https://github.com/deathcrafter/ASimpleVisualizer]

[DeviantArt]
Meter=Image
ImageName=#@#Images\deviantart
H=25
W=25
X=12
Y=175
LeftMouseUpAction=[!CommandMeasure DeviceID "GetAudioDevices()"]

[Title2]
Meter=String
Text=A Simple Visualizer
FontSize=20
FontFace=Comfortaa Bold
X=56
Y=10
StringAlign=Left
AntiAlias=1