[Title1]
Meter=String
Text=Version 1.00
FontSize=(9*[#Scale])
X=(12*[#Scale])
Y=(379*[#Scale])
FontFace=Comfortaa Bold
Angle=(Rad(270))
AntiAlias=1

[deathcrafter]
Meter=String
Text=death.crafter
FontSize=(9*[#Scale])
X=(26*[#Scale])
Y=(367*[#Scale])
FontFace=Comfortaa Bold
Angle=(Rad(270))
AntiAlias=1

[Unlicense]
Meter=Image
ImageName=#@#Images\unlicensed
ImageTint=0,0,0
H=(11*[#Scale])
W=(11*[#Scale])
X=(27*[#Scale])
Y=(367*[#Scale])

[Github]
Meter=Image
ImageName=#@#Images\github
H=(25*[#Scale])
W=(25*[#Scale])
X=(12*[#Scale])
Y=(215*[#Scale])
LeftMouseUpAction=[https://github.com/deathcrafter/ASimpleVisualizer]

[DeviantArt]
Meter=Image
ImageName=#@#Images\deviantart
H=(25*[#Scale])
W=(25*[#Scale])
X=(12*[#Scale])
Y=(175*[#Scale])
LeftMouseUpAction=[!CommandMeasure DeviceID "GetAudioDevices()"]

[Title2]
Meter=String
Text=A Simple Visualizer
FontSize=(20*[#Scale])
FontFace=Comfortaa Bold
X=(56*[#Scale])
Y=(10*[#Scale])
StringAlign=Left
AntiAlias=1